### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by wxyzed123** [linuxtech-scripts/f5_geo_update#1]
Hi, I added the script to a BigIP v14.1.2.8.  Updated the creds, tested connectivity with curl (203 response) but get a login failed response.  Manually tested the creds I was using too.  Any idea if the F5 site has changed and the script needs updating?

Thanks.

**Comment by linuxtech-scripts** [comment]
The Download site has changed somewhat, so the login detection failed.

I've updated the script to adapt.

Sorry it has taken some time for me to see this ...
